core/urls.py
from django.conf.urls import url

from history import views

urlpatterns = [
    url(regex=r'^$',
        view=views.DashboardView.as_view(),
        name='dashboard'),
]

history/urls.py
from django.conf.urls import url

from history import views

urlpatterns = [
    url(regex=r'^api/start/(?P<pk>\d+)/$',
        view=views.HistoryApiStart.as_view(),
        name='api_history_start'),
    url(regex=r'^api/finish/(?P<pk>\d+)/$',
        view=views.HistoryApiFinish.as_view(),
        name='api_history_finish'),
    url(regex=r'^api/dashboard/$',
        view=views.ApiDashboard.as_view(),
        name='api_dashboard'),
    url(regex=r'^dashboard/$',
        view=views.DashboardView.as_view(),
        name='dashboard'),
    url(regex=r'^api/order/(?P<pk>\d+)/productivity/$',
        view=views.ApiOrderProductivity.as_view(),
        name='api_history_order_productivity'),
    url(regex=r'^order/productivity/$',
        view=views.OrderProductivityView.as_view(),
        name='history_order_productivity'),
]

smartwork/urls.py
from django.conf.urls import include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('core.urls', namespace='core')),
    url(r'^orders/', include('order.urls', namespace='order')),
    url(r'^items/', include('item.urls', namespace='item')),
    url(r'^desks/', include('desk.urls', namespace='desk')),
    url(r'^history/', include('history.urls', namespace='history')),
    url(r'^manager/', include('manager.urls', namespace='manager')),
]

history/models.py
# coding=utf-8
from __future__ import unicode_literals
from django.utils.translation import ugettext as _
from django.db import models


class History(models.Model):
    start = models.DateTimeField(_('Início'))
    end = models.DateTimeField(_('Fim'), null=True, blank=True)

    # relations
    order_desk = models.ForeignKey(
        to='order.OrderDesk', related_name='histories')

    class Meta:
        verbose_name = _(u'Order Desk History')
        verbose_name_plural = _(u'Order Desk History')

order/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext as _
from django.db import models


class Order(models.Model):
    CREATED = 'created'
    STARTED = 'started'
    STOPED = 'stoped'
    FINISHED = 'finished'
    STATUS_CHOICES = (
        (CREATED, 'Criada'),
        (STARTED, 'Iniciada'),
        (STOPED, 'Pausada'),
        (FINISHED, 'Terminada'),
    )
    quantity = models.IntegerField(_('Quantidade'))
    deadline = models.IntegerField(_('Prazo (dias)'))
    status = models.CharField(
        _('Status'), max_length=20, choices=STATUS_CHOICES,
        default=STARTED, blank=True)

    loss = models.IntegerField(_('Prejuízo'), null=True, blank=True)
    items_produced = models.IntegerField(null=True, blank=True)

    # relations
    item = models.ForeignKey(
        to='item.Item', related_name='orders',
        null=True, blank=True)
    desks = models.ManyToManyField(
        to='desk.Desk', through='order.OrderDesk',
        blank=True, related_name='orders',
        verbose_name='Estações de Trabalho')

    class Meta:
        verbose_name = _(u'Order')
        verbose_name_plural = _(u'Orders')

    def __unicode__(self):
        return self.item.name

    def get_absolute_url(self):
        return reverse('order:detail', kwargs={'pk': self.pk})

    def get_update_url(self):
        return reverse('order:update', kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse('order:delete', kwargs={'pk': self.pk})

    def get_item_per_desk(self):
        return self.quantity // self.order_desks.count()

    def get_item_per_day(self):
        return self.get_item_per_desk() // self.deadline

    def get_left_items(self):
        return self.quantity - (self.quantity * 0.8)

    def get_results_achieved(self):
        percentage = (self.items_produced * 100) // self.quantity
        return percentage


class OrderDesk(models.Model):
    order = models.ForeignKey(to='order.Order', related_name='order_desks')
    desk = models.ForeignKey(to='desk.Desk', related_name='order_desks')

    class Meta:
        verbose_name = _(u'Order Desk')
        verbose_name_plural = _(u'Order Desks')

    @property
    def status(self):
        history = self.last_history
        if not history:
            return 'inactive'
        elif history.start and not history.end:
            return 'working'
        return 'idle'

    @property
    def get_status_display(self):
        return {
            'inactive': 'Inativa',
            'working': 'Em Atividade',
            'idle': 'Ociosa',
        }.get(self.status)
        # history = self.last_history
        # if not history:
        #     return 'Inativa'

        # if history.start and not history.end:
        #     return 'Em atividade'
        # else:
        #     return 'Ocioso'

    @property
    def last_history(self):
        return self.histories.last()

history/views.py
from django.db.models import Q, Count
from django.utils import timezone
from rest_framework.views import APIView
from rest_framework.response import Response
from django.conf import settings

from vanilla import TemplateView

from desk.models import Desk
from order.models import OrderDesk, Order
from history.models import History


def now():
    return timezone.localtime(timezone.now())


class HistoryApiStart(APIView):
    def post(self, request, pk):
        order_desk = OrderDesk.objects.filter(
            desk__pk=pk, order__status=Order.STARTED
        ).last()
        History.objects.create(start=now(), order_desk=order_desk)
        return Response({})


class HistoryApiFinish(APIView):
    def post(self, request, pk):
        order_desk = OrderDesk.objects.filter(
            desk__pk=pk, order__status=Order.STARTED
        ).last()
        history = History.objects.filter(
            order_desk=order_desk
        ).last()
        history.end = now()
        history.save()

        desk = Desk.objects.get(pk=pk)
        if desk.is_last_desk:
            order = Order.objects.get(pk=order_desk.order.pk)
            if order.items_produced:
                order.items_produced += 1
            else:
                order.items_produced = 0
            order.save()

        return Response({})


class ApiDashboard(APIView):
    def get(self, request):
        orders = Order.objects.filter(status=Order.STARTED)
        started_desks = 0
        idle_desks = 0
        inactive_desks = 0
        desks = OrderDesk.objects.filter(
            order__pk__in=orders.values_list('pk', flat=True))
        desk_list = []
        for desk in desks:
            if desk.status == "working":
                started_desks += 1
            if desk.status == "idle":
                idle_desks += 1
            else:
                inactive_desks += 1

            end = start = None
            if desk.last_history:
                start = desk.last_history.start
                end = desk.last_history.end

            dic_desk = {
                "pk": desk.pk,
                "desk_number": desk.desk.number,
                "start": start.isoformat() if start else None,
                "finish": end.isoformat() if end else None,
                "status": desk.status,
                "formatted_status": desk.get_status_display,
                "order": desk.order_id
            }
            desk_list.append(dic_desk)

        return Response({
            "order_count": orders.count(),
            "total_left": 1200 - 160,
            "started_desk": started_desks,
            "idle_desk": idle_desks,
            "inactive_desk": inactive_desks,
            "total_desk": (
                started_desks + idle_desks + inactive_desks
            ),
            "desks": desk_list
        })


class ApiOrderProductivity(APIView):
    def get(self, request, pk):
        order = Order.objects.get(pk=pk)

        extra_args = {
            'date': 'history_history.end::timestamp::date'
        }
        db_engine = settings.DATABASES.get('default').get('ENGINE')
        if db_engine.endswith('sqlite3'):
            extra_args.update({
                'date': 'date(end)'
            })

        histories = History.objects.filter(
            Q(end__isnull=False) &
            Q(order_desk__order=order) &
            Q(order_desk__desk__next_desk__isnull=True) &
            Q(order_desk__desk__previous_desk__isnull=False)
        ).extra(select=extra_args).values('date').annotate(total=Count('id'))

        def accumulate_total(histories):
            total = 0
            for x in histories:
                total += x
                yield total

        return Response({
            'pk': order.pk,
            'item': order.item.name,
            'deadline': order.deadline,
            'quantity': order.quantity,
            'histories': accumulate_total(
                [history.get('total') for history in histories]
            ),
        })


class DashboardView(TemplateView):
    template_name = 'history/dashboard.html'


class OrderProductivityView(TemplateView):
    template_name = 'history/order_productivity.html'

    def get_context_data(self, **kwargs):
        context = super(OrderProductivityView, self).get_context_data(**kwargs)
        context.update(
            orders=Order.objects.all()
        )
        return context

history/templates/history/dashboard.html
{% extends "core/base.html" %}

{% load static %}

{% block ngapp %}ng-app="myApp"{% endblock ngapp %}
{% block ngcontroller %}ng-controller="CtrlIndex"{% endblock ngcontroller %}

{% block content %}
    {% verbatim %}
        <div class="block-header">
            <h2>Painel de Visão Geral</h2>
        </div>
        <div class="row clearfix">
            <div class="col-sm-2 col-xs-12">
                <div class="info-box bg-indigo">
                    <div class="icon">
                        <i class="material-icons">multiline_chart</i>
                    </div>
                    <div class="content">
                        <div class="text text-upper">Pedidos</div>
                        <div class="number">{{ retorno.order_count }}</div>
                    </div>
                </div>
            </div>
            <div class="col-sm-2 col-xs-12">
                <div class="info-box bg-teal">
                    <div class="icon">
                        <i class="material-icons">show_chart</i>
                    </div>
                    <div class="content">
                        <div class="text text-upper">Restando</div>
                        <div class="number">
                            {{ retorno.total_left }}
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-2 col-xs-12">
                <div class="info-box bg-blue">
                    <div class="icon">
                        <i class="material-icons">work</i>
                    </div>
                    <div class="content">
                        <div class="text text-upper">Mesas</div>
                        <div class="number ">{{ retorno.total_desk }}</div>
                    </div>
                </div>
            </div>
            <div class="col-sm-2 col-xs-4">
                <div class="info-box bg-light-green">
                    <div class="icon">
                        <i class="material-icons">alarm_on</i>
                    </div>
                    <div class="content">
                        <div class="text text-upper">Ativas</div>
                        <div class="number">{{ retorno.started_desk }}</div>
                    </div>
                </div>
            </div>
            <div class="col-sm-2 col-xs-4">
                <div class="info-box bg-orange">
                    <div class="icon">
                        <i class="material-icons">alarm_off</i>
                    </div>
                    <div class="content">
                        <div class="text text-upper">Ociosas</div>
                        <div class="number ">{{ retorno.idle_desk }}</div>
                    </div>
                </div>
            </div>
            <div class="col-sm-2 col-xs-4">
                <div class="info-box bg-grey">
                    <div class="icon">
                        <i class="material-icons">timer_off</i>
                    </div>
                    <div class="content">
                        <div class="text text-upper">Inativas</div>
                        <div class="number ">{{ retorno.inactive_desk }}</div>
                    </div>
                </div>
            </div>
        </div>
        <!-- #END# Widgets -->

        <!-- TESTE -->
        <div class="row clearfix">
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12" ng-repeat="desk in desks">
                <div class="info-box-3 bg-light-green" ng-if="desk.status == 'working'">
                    <div class="icon">
                        <i class="material-icons">alarm_on</i>
                    </div>
                    <div class="content">
                        <div class="text text-upper">
                            Mesa {{ desk.desk_number }}
                            &#8226;
                            Pedido #{{ desk.order }}
                        </div>
                        <div class="number">
                            {{ desk.formatted_status }}
                        </div>
                    </div>
                </div>

                <div class="info-box-3 bg-grey" ng-if="desk.status == 'inactive'">
                    <div class="icon">
                        <i class="material-icons">timer_off</i>
                    </div>
                    <div class="content">
                        <div class="text text-upper">
                            Mesa {{ desk.desk_number }}
                            &#8226;
                            Pedido #{{ desk.order }}
                        </div>
                        <div class="number">
                            {{ desk.formatted_status }}
                        </div>
                    </div>
                </div>

                <div class="info-box-3 bg-orange" ng-if="desk.status == 'idle'">
                    <div class="icon">
                        <i class="material-icons">alarm_off</i>
                    </div>  
                    <div class="content">
                        <div class="text text-upper">
                            Mesa {{ desk.desk_number }}
                            &#8226;
                            Pedido #{{ desk.order }}
                        </div>
                        <div class="number">
                            {{ desk.formatted_status }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endverbatim %}
{% endblock content %}

{% block extra_js %}
    <script type="text/javascript" src="{% static 'js/moments.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/angular.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/angular-moment.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/ctrl.js' %}"></script>
{% endblock extra_js %}

history/templates/history/order_productivity.html
{% extends "core/base.html" %}

{% load static %}

{% block content %}
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2 class="text-upper">Produtividade do Pedido</h2>
                    <small>You can use material design colors</small>

                    <div class="pull-right">
                        <label for="id_order">Pedidos</label>
                        <select id="id_order" class="selectpicker" data-live-search="true">
                            {% for order in orders %}
                                <option value="{{ order.pk }}">{{ order.item }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="body">
                    <canvas class="line_chart" height="150"></canvas>
                </div>
            </div>
        </div>
    </div>
    <!-- #END# Basic Table -->
{% endblock %}

{% block extra_js %}
    <script type="text/javascript" src="{% static 'js/moments.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/angular.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/angular-moment.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/ctrl.js' %}"></script>
    <script type="text/javascript">
    $(function () {
        //Criar as labels do gráfico
        function dividirDias(prazo){
            var dias = [];
            for (var i = 0; i < prazo; i++) {
                dias[i] = "Dia "+(i+1);
            }
            return dias;
        }

        //calcula o mínimo que pode ser feito por dia, para que seja entregue no prazo correto
        function calcularProducaoMedia(prazo, total) {
            var prod = [];
            var prodDia = total/prazo;
            for (var i = 0; i < prazo; i++) {
                if(i == 0){
                    prod[i] = prodDia;
                } else{
                    prod[i] = prod[i-1] + prodDia;
                }
            }
            return prod;
        }

        // Gera o gráfico
        function getChartJs(type, result) {
            var config = null;
            config = {
                type: 'line',
                data: {
                    labels: dividirDias(result.deadline),
                    datasets: [{
                        label: "Produtividade",
                        data: result.histories,
                        borderColor: 'rgba(0, 188, 212, 0.75)',
                        backgroundColor: 'rgba(0, 188, 212, 0.3)',
                        pointBorderColor: 'rgba(0, 188, 212, 0)',
                        pointBackgroundColor: 'rgba(0, 188, 212, 0.9)',
                        pointBorderWidth: 1
                    }, {
                        label: "Meta Diária",
                        data: calcularProducaoMedia(result.deadline, result.quantity),
                        borderColor: 'rgba(50, 50, 50, 0.75)',
                        backgroundColor: 'rgba(50, 50, 50, 0.3)',
                        pointBorderColor: 'rgba(50, 50, 50, 0)',
                        pointBackgroundColor: 'rgba(50, 50, 50, 0.9)',
                        pointBorderWidth: 1
                    }]
                },
                options: {
                    responsive: true,
                    legend: false
                }
            };
            return config;
        }
        function reloadChart() {
            var order_id = $('#id_order').val();
            $.ajax({
                method: 'GET',
                url: '/history/api/order/' + order_id + '/productivity/'
            }).success(function (data) {
                result = data;
                new Chart(
                    $(".line_chart")[0].getContext("2d"), getChartJs('line', result)
                );
            });
        }

        //reloadChart();
        $('#id_order').change(function() {
            reloadChart();
        });
    });
    </script>
{% endblock extra_js %}