core/urls.py
from django.conf.urls import url

from history import views

urlpatterns = [
    url(regex=r'^$',
        view=views.DashboardView.as_view(),
        name='dashboard'),
]

desk/urls.py
from django.shortcuts import render
from django.conf.urls import url

from desk import views

urlpatterns = [
    url(regex=r'^$',
        view=views.DeskList.as_view(),
        name='list'),
    url(regex=r'^create/$',
        view=views.DeskCreate.as_view(),
        name='create'),
    url(regex=r'^(?P<pk>\d+)/$',
        view=views.DeskDetail.as_view(),
        name='detail'),
    url(regex=r'^(?P<pk>[\w-]+)/update/$',
        view=views.DeskUpdate.as_view(),
        name='update'),
    url(regex=r'^(?P<pk>[\w-]+)/delete/$',
        view=views.DeskDelete.as_view(),
        name='delete'),
]

smartwork/urls.py
from django.conf.urls import include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('core.urls', namespace='core')),
    url(r'^orders/', include('order.urls', namespace='order')),
    url(r'^items/', include('item.urls', namespace='item')),
    url(r'^desks/', include('desk.urls', namespace='desk')),
    url(r'^history/', include('history.urls', namespace='history')),
    url(r'^manager/', include('manager.urls', namespace='manager')),
]

desk/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext as _
from django.db import models


class Desk(models.Model):
    CREATED = 'created'
    STARTED = 'started'
    STOPED = 'stoped'
    FINISHED = 'finished'
    STATUS_CHOICES = (
        (CREATED, 'Criada'),
        (STARTED, 'Iniciada'),
        (STOPED, 'Pausada'),
        (FINISHED, 'Terminada'),
    )

    name = models.CharField(_('Nome'), max_length=200)
    number = models.CharField(_('Numero'), max_length=200)
    status = models.CharField(
        _('Status'), max_length=20, choices=STATUS_CHOICES,
        default=CREATED, blank=True)

    # relations
    previous_desk = models.OneToOneField(
        verbose_name='Estação Anterior',
        to='self', null=True, blank=True, related_name='next')
    next_desk = models.OneToOneField(
        verbose_name='Estação Seguinte',
        to='self', null=True, blank=True, related_name='previous')

    class Meta:
        verbose_name = _(u'Desk')
        verbose_name_plural = _(u'Desks')

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('desk:detail', kwargs={'pk': self.pk})

    def get_update_url(self):
        return reverse('desk:update', kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse('desk:delete', kwargs={'pk': self.pk})

    @property
    def is_first_desk(self):
        return not self.previous_desk and self.next_desk

    @property
    def is_last_desk(self):
        return not self.next_desk and self.previous_desk

desk/forms.py
from django import forms

from desk.models import Desk


class DeskForm(forms.ModelForm):
    class Meta:
        fields = '__all__'
        model = Desk

desk/views.py
from django.shortcuts import render
from django.utils.translation import ugettext as _
from django.core.urlresolvers import reverse

from desk.forms import DeskForm

from vanilla import model_views as views

from desk.models import Desk


class BaseDeskView():
    model = Desk
    form_class = DeskForm
    lookup_field = 'pk'


class DeskList(BaseDeskView, views.ListView):
    template_name = 'desk/list.html'
    page_title = _(u'Desks')


class DeskCreate(BaseDeskView, views.CreateView):
    template_name = 'desk/form.html'


class DeskDetail(BaseDeskView, views.DetailView):
    template_name = 'desk/detail.html'


class DeskUpdate(BaseDeskView, views.UpdateView):
    template_name = 'desk/form.html'


class DeskDelete(BaseDeskView, views.DeleteView):
    template_name = 'desk/delete.html'

    def get_success_url(self):
        return reverse('desk:list')

desk/templates/desk/delete.html
{% extends "core/base.html" %}

{% block content %}
    <div class="row clearfix">
        <ol class="breadcrumb">
            <li>
                <a href="{% url 'core:dashboard' %}">
                    <i class="material-icons">home</i> Início
                </a>
            </li>
            <li>
                <a href="{% url 'desk:list' %}">
                    <i class="material-icons">work</i> Estações
                </a>
            </li>
            <li class="active">
                Remover Estação "{{ object.name }}"
            </li>
        </ol>
    </div>

    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header bg-deep-orange">
                    <h2>
                        <span class="text-upper">Remover Estação "{{ object.name }}"</span>
                        <small>Basic example without any additional modification classes</small>
                    </h2>
                </div>
                <div class="body">
                    <h4 class="align-center">Tem certeza que deseja remover essa mesa?</h4>

                    <div class="align-center p-t-20 p-b-30">
                        <span>&#8226;</span>
                    </div>

                    <form method="POST">
                      {% csrf_token %}
                      <div class="align-center">
                          <a class="btn btn-lg p-l-50 p-r-50 waves-effect btn-default" href="{% url 'desk:list' %}">
                              <i class="material-icons">cancel</i>
                              Cancelar
                          </a>
                          &nbsp;
                          <button type="submit" class="btn btn-lg p-l-50 p-r-50 waves-effect bg-indigo">
                              <i class="material-icons">check</i>
                              Remover
                          </button>
                      </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

desk/templates/desk/form.html
{% extends "core/base.html" %}

{% load widget_tweaks %}

{% block content %}
    <div class="row clearfix">
        <ol class="breadcrumb">
            <li>
                <a href="{% url 'core:dashboard' %}">
                    <i class="material-icons">home</i> Início
                </a>
            </li>
            <li>
                <a href="{% url 'desk:list' %}">
                    <i class="material-icons">work</i> Estações
                </a>
            </li>
            {% if form.instance.pk %}
                <li class="active">
                    Alterar Estação "{{ object.name }}"
                </li>
            {% else %}
                <li class="active">
                    Adicionar Estação
                </li>
            {% endif %}
        </ol>
    </div>

    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header {% if form.instance.pk %}bg-cyan{% else %}bg-indigo{% endif %}">
                    {% if form.instance.pk %}
                        <h2 class="text-upper">Alterar Estação "{{ object.name }}"</h2>
                    {% else %}
                        <h2 class="text-upper">Adicionar Estação</h2>
                    {% endif %}
                    <small>You can use material design colors</small>
                </div>
                <div class="body table-responsive">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}

                        <div class="input-group input-group-lg">
                          {{ form.name.label_tag }}
                          <div class="form-line">
                            {% render_field form.name|add_class:'form-control' placeholder='Ex.: Estação de Costura' autofocus='autofocus' %}
                          </div>
                        </div>

                        <div class="input-group input-group-lg force-z-index">
                            {{ form.previous_desk.label_tag }}

                            <div class="form-line">
                                {% render_field form.previous_desk|add_class:'form-control selectpicker' data-live-search='true' %}
                            </div>
                        </div>

                        <div class="input-group input-group-lg">
                            {{ form.next_desk.label_tag }}

                            <div class="form-line">
                                {% render_field form.next_desk|add_class:'form-control selectpicker' data-live-search='true' %}
                            </div>
                        </div>

                        <div class="input-group input-group-lg">
                          {{ form.number.label_tag }}
                          <div class="form-line">
                            {% render_field form.number|add_class:'form-control' placeholder='Número Identificador' %}
                          </div>
                        </div>

                        <div class="align-center p-t-10 p-b-30">
                            <span>&#8226;</span>
                        </div>

                        <div class="input-group align-center">
                            <a class="btn btn-lg p-l-50 p-r-50 waves-effect btn-default" href="{% url 'desk:list' %}">
                                <i class="material-icons">cancel</i>
                                Cancelar
                            </a>
                            &nbsp;
                            <button type="submit" class="btn btn-lg p-l-50 p-r-50 waves-effect bg-indigo">
                                <i class="material-icons">check</i>
                                Salvar
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- #END# Basic Table -->
{% endblock %}

desk/templates/desk/list.html
{% extends "core/base.html" %}

{% block breadcrumbs %}
{% endblock breadcrumbs %}

{% block content %}
    <div class="row clearfix">
        <ol class="breadcrumb">
            <li>
                <a href="{% url 'core:dashboard' %}">
                    <i class="material-icons">home</i> Início
                </a>
            </li>
            <li class="active">
                <i class="material-icons">work</i> Estações
            </li>
        </ol>
    </div>

    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        <span class="text-upper">Estações</span>
                        <a class="btn bg-indigo btn-sm pull-right" href="{% url 'desk:create' %}">
                            <i class="material-icons">add</i>
                            <span>Adicionar Estação</span>
                        </a>
                        <small>
                            {% with object_list.count as total %}
                                {{ total }} mesa{{ total|pluralize }} adicionada{{ total|pluralize }}.
                            {% endwith %}
                        </small>
                    </h2>
                </div>
                <div class="body table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Nome</th>
                                <th>Número</th>
                                <th>Status</th>
                                <th>Estação Anterior</th>
                                <th>Estação Seguinte</th>
                                <th>Ações</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for object in object_list %}
                                <tr>
                                    <td>{{ object.name }}</td>
                                    <td>{{ object.number }}</td>
                                    <td>{{ object.get_status_display }}</td>
                                    <td>
                                        {% if object.previous_desk %}
                                            <a href="{{ object.previous_desk.get_absolute_url }}">{{ object.previous_desk }}</a>
                                        {% else %}
                                            -
                                        {% endif %}
                                    </td>
                                    <td>
                                        {% if object.next_desk %}
                                            <a href="{{ object.next_desk.get_absolute_url }}">{{ object.next_desk }}</a>
                                        {% else %}
                                            -
                                        {% endif %}
                                    </td>
                                    <td>
                                        <a class="btn btn-sm bg-cyan" href="{{ object.get_update_url }}">
                                        <i class="material-icons">edit</i>
                                            Atualizar
                                        </a>
                                        <a class="btn btn-sm bg-deep-orange" href="{{ object.get_delete_url }}">
                                            <i class="material-icons">delete_forever</i>
                                            Remover
                                        </a>
                                    </td>
                                </tr>
                            {% empty %}
                                <tr>
                                    <td colspan="3">
                                        Nenhuma Estação encontrada.
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}