core/urls.py
from django.conf.urls import url

from history import views

urlpatterns = [
    url(regex=r'^$',
        view=views.DashboardView.as_view(),
        name='dashboard'),
]

desk/urls.py
from django.shortcuts import render
from django.conf.urls import url

from desk import views

urlpatterns = [
    url(regex=r'^$',
        view=views.DeskList.as_view(),
        name='list'),
    url(regex=r'^create/$',
        view=views.DeskCreate.as_view(),
        name='create'),
    url(regex=r'^(?P<pk>\d+)/$',
        view=views.DeskDetail.as_view(),
        name='detail'),
    url(regex=r'^(?P<pk>[\w-]+)/update/$',
        view=views.DeskUpdate.as_view(),
        name='update'),
    url(regex=r'^(?P<pk>[\w-]+)/delete/$',
        view=views.DeskDelete.as_view(),
        name='delete'),
]

history/urls.py
from django.conf.urls import url

from history import views

urlpatterns = [
    url(regex=r'^api/start/(?P<pk>\d+)/$',
        view=views.HistoryApiStart.as_view(),
        name='api_history_start'),
    url(regex=r'^api/finish/(?P<pk>\d+)/$',
        view=views.HistoryApiFinish.as_view(),
        name='api_history_finish'),
    url(regex=r'^api/dashboard/$',
        view=views.ApiDashboard.as_view(),
        name='api_dashboard'),
    url(regex=r'^dashboard/$',
        view=views.DashboardView.as_view(),
        name='dashboard'),
    url(regex=r'^api/order/(?P<pk>\d+)/productivity/$',
        view=views.ApiOrderProductivity.as_view(),
        name='api_history_order_productivity'),
    url(regex=r'^order/productivity/$',
        view=views.OrderProductivityView.as_view(),
        name='history_order_productivity'),
]

smartwork/urls.py
from django.conf.urls import include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('core.urls', namespace='core')),
    url(r'^orders/', include('order.urls', namespace='order')),
    url(r'^items/', include('item.urls', namespace='item')),
    url(r'^desks/', include('desk.urls', namespace='desk')),
    url(r'^history/', include('history.urls', namespace='history')),
    url(r'^manager/', include('manager.urls', namespace='manager')),
]

core/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

core/views.py
from vanilla import TemplateView


class IndexView(TemplateView):
    template_name = 'core/index.html'

core/templates/core/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>Smartwork | Produtividade em Tempo Real</title>
    <!-- Favicon-->
    <link rel="icon" href="favicon.ico" type="image/x-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">

    <!-- Bootstrap Core Css -->
    <link href="{% static 'plugins/bootstrap/css/bootstrap.css' %}" rel="stylesheet">

    <!-- Waves Effect Css -->
    <link href="{% static 'plugins/node-waves/waves.css' %}" rel="stylesheet" />

    <!-- Animation Css -->
    <link href="{% static 'plugins/animate-css/animate.css' %}" rel="stylesheet" />

    <!-- Colorpicker Css -->
    <link href="{% static 'plugins/bootstrap-colorpicker/css/bootstrap-colorpicker.css'%}" rel="stylesheet" />

    <!-- Preloader Css -->
    <link href="{% static 'plugins/material-design-preloader/md-preloader.css' %}" rel="stylesheet" />

    <!-- Morris Chart Css-->
    <link href="{% static 'plugins/morrisjs/morris.css' %}" rel="stylesheet" />

    <!-- Dropzone Css -->
    <link href="{% static 'plugins/dropzone/dropzone.css' %}" rel="stylesheet">

    <!-- Multi Select Css -->
    <link href="{% static 'plugins/multi-select/css/multi-select.css' %}" rel="stylesheet">

    <!-- Bootstrap Spinner Css -->
    <link href="{% static 'plugins/jquery-spinner/css/bootstrap-spinner.css' %}" rel="stylesheet">

    <!-- Bootstrap Tagsinput Css -->
    <link href="{% static 'plugins/bootstrap-tagsinput/bootstrap-tagsinput.css' %}" rel="stylesheet">

    <!-- Bootstrap Select Css -->
    <link href="{% static 'plugins/bootstrap-select/css/bootstrap-select.css' %}" rel="stylesheet" />

    <!-- noUISlider Css -->
    <link href="{% static 'plugins/nouislider/nouislider.min.css' %}" rel="stylesheet" />

    <!-- Custom Css -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <!-- AdminBSB Themes. You can choose a theme from css/themes instead of get all themes -->
    <link href="{% static 'css/themes/all-themes.css' %}" rel="stylesheet" />

    <style type="text/css">
        .text-upper {
            text-transform: uppercase;
        }

        .force-z-index {
            z-index: 9;
        }

        input.form-control {
            z-index: 0 !important;
        }

        .info-box-3 {
            height: 80px;
        }
    </style>
</head>

<body class="theme-indigo" {% block ngapp %}{% endblock ngapp %}>
    <!-- Page Loader -->
    <div class="page-loader-wrapper">
        <div class="loader">
            <div class="md-preloader pl-size-md">
                <svg viewbox="0 0 75 75">
                    <circle cx="37.5" cy="37.5" r="33.5" class="pl-indigo" stroke-width="4" />
                </svg>
            </div>
            <p>Carregando...</p>
        </div>
    </div>
    <!-- #END# Page Loader -->
    <!-- Overlay For Sidebars -->
    <div class="overlay"></div>
    <!-- #END# Overlay For Sidebars -->
    <!-- Top Bar -->
    <nav class="navbar">
        <div class="container-fluid">
            <div class="navbar-header">
                <a href="javascript:void(0);" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false"></a>
                <a href="javascript:void(0);" class="bars"></a>
                <a class="navbar-brand" href="{% url 'core:dashboard' %}">Smartwork</a>
            </div>
        </div>
    </nav>
    <!-- #Top Bar -->
    <section>
        <!-- Left Sidebar -->
        <aside id="leftsidebar" class="sidebar">
            <!-- Menu -->
            <div class="menu">
                <ul class="list">
                    <li class="header">Menu de Navegação</li>
                    <li>
                        <a href="{% url 'history:dashboard' %}">
                            <i class="material-icons">dashboard</i>
                            <span>Painel de Visão Geral</span>
                        </a>
                    </li>
                    <li>
                        <a href="javascript:void(0);" class="menu-toggle">
                            <i class="material-icons">multiline_chart</i>
                            <span>Pedidos</span>
                        </a>
                        <ul class="ml-menu">
                            <li>
                                <a href="{% url 'order:list' %}">
                                    <span>Listar</span>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'order:create' %}">
                                    <span>Adicionar</span>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="javascript:void(0);" class="menu-toggle">
                            <i class="material-icons">widgets</i>
                            <span>Itens</span>
                        </a>
                        <ul class="ml-menu">
                            <li>
                                <a href="{% url 'item:list' %}">
                                    <span>Listar</span>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'item:create' %}">
                                    <span>Adicionar</span>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="javascript:void(0);" class="menu-toggle">
                            <i class="material-icons">work</i>
                            <span>Estações de Trabalho</span>
                        </a>
                        <ul class="ml-menu">
                            <li>
                                <a href="{% url 'desk:list' %}">
                                    <span>Listar</span>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'desk:create' %}">
                                    <span>Adicionar</span>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="javascript:void(0);" class="menu-toggle">
                            <i class="material-icons">supervisor_account</i>
                            <span>Gerencia de Produção</span>
                        </a>
                        <ul class="ml-menu">
                            <li>
                                <a href="{% url 'manager:list' %}">
                                    <span>Listar</span>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'manager:create' %}">
                                    <span>Adicionar</span>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="javascript:void(0);" class="menu-toggle">
                            <i class="material-icons">show_chart</i>
                            <span>Relatórios</span>
                        </a>
                        <ul class="ml-menu">
                            <li>
                                <a href="{% url 'history:history_order_productivity' %}">
                                    <span>Produtividade do Pedido</span>
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
            <!-- #Menu -->
            <!-- Footer -->
            <div class="legal">
                <div class="copyright">
                    &copy; 2016 <a href="javascript:void(0);">Smartwork</a>.
                </div>
            </div>
            <!-- #Footer -->
        </aside>
        <!-- #END# Left Sidebar -->
    </section>

    <section class="content">
        <div class="container-fluid" {% block ngcontroller %}{% endblock ngcontroller %}>
            {% block content %}
            {% endblock %}
        </div>
    </section>

    <!-- Jquery Core Js -->
    <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>

    <!-- Bootstrap Core Js -->
    <script src="{% static 'plugins/bootstrap/js/bootstrap.js' %}"></script>

    <!-- Select Plugin Js -->
    <script src="{% static 'plugins/bootstrap-select/js/bootstrap-select.js' %}"></script>

    <!-- Slimscroll Plugin Js -->
    <script src="{% static 'plugins/jquery-slimscroll/jquery.slimscroll.js' %}"></script>

    <!-- Bootstrap Colorpicker Js -->
    <script src="{% static 'plugins/bootstrap-colorpicker/js/bootstrap-colorpicker.js' %}"></script>

    <!-- Dropzone Plugin Js -->
    <script src="{% static 'plugins/dropzone/dropzone.js' %}"></script>

    <!-- Input Mask Plugin Js -->
    <script src="{% static 'plugins/jquery-inputmask/jquery.inputmask.bundle.js' %}"></script>

    <!-- Multi Select Plugin Js -->
    <script src="{% static 'plugins/multi-select/js/jquery.multi-select.js' %}"></script>

    <!-- Jquery Spinner Plugin Js -->
    <script src="{% static 'plugins/jquery-spinner/js/jquery.spinner.js' %}"></script>

    <!-- Bootstrap Tags Input Plugin Js -->
    <script src="{% static 'plugins/bootstrap-tagsinput/bootstrap-tagsinput.js' %}"></script>

    <!-- noUISlider Plugin Js
    <script src="{% static 'plugins/nouislider/nouislider.js' %}"></script>
    -->

    <!-- Waves Effect Plugin Js -->
    <script src="{% static 'plugins/node-waves/waves.js' %}"></script>

    <!-- Jquery CountTo Plugin Js -->
    <script src="{% static 'plugins/jquery-countto/jquery.countTo.js' %}"></script>

    <!-- Morris Plugin Js -->
    <script src="{% static 'plugins/raphael/raphael.min.js' %}"></script>
    <script src="{% static 'plugins/morrisjs/morris.js' %}"></script>

    <!-- ChartJs -->
    <script src="{% static 'plugins/chartjs/Chart.bundle.js' %}"></script>

    <!-- Flot Charts Plugin Js -->
    <script src="{% static 'plugins/flot-charts/jquery.flot.js' %}"></script>
    <script src="{% static 'plugins/flot-charts/jquery.flot.resize.js' %}"></script>
    <script src="{% static 'plugins/flot-charts/jquery.flot.pie.js' %}"></script>
    <script src="{% static 'plugins/flot-charts/jquery.flot.categories.js' %}"></script>
    <script src="{% static 'plugins/flot-charts/jquery.flot.time.js' %}"></script>

    <!-- Sparkline Chart Plugin Js -->
    <script src="{% static 'plugins/jquery-sparkline/jquery.sparkline.js' %}"></script>

    <!-- Custom Js -->
    <script src="{% static 'js/admin.js' %}"></script>
    <script src="{% static 'js/pages/forms/advanced-form-elements.js' %}"></script>

    <!-- Demo Js -->
    <script src="{% static 'js/demo.js' %}"></script>

    {% block extra_js %}{% endblock extra_js %}
</body>

</html>

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block content %}
    <div class="block-header">
        <h2>Início</h2>
    </div>
{% endblock %}